### ISSUE TITLE
Remove references to the dockerfiles tab

### ISSUE THREAD

**Issue by whostolebenfrog** [atomisthq/docs#367]

**Comment by slimslenderslacks** [comment]
@whostolebenfrog - I replaced some images in the getting-started guide

Are there other locations where you're seeing the dockerfiles tab?

**Comment by whostolebenfrog** [comment]
@slimslenderslacks No - I think I cleaned everything else up. I left the getting started guide as you were working on it. So we should be good here.

**Comment by slimslenderslacks** [comment]
Okay, thanks, I've cleaned up the images in the getting started guide so we should be good.  Thanks
